language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt > /dev/null # discard installation output
  - pip install .
  - pip install --upgrade pytest-cov pytest
  - pip install codecov
script:
  - for file in neurodiffeq/tests/test*py; do pytest --cov-report term --cov=$file; done
after_success:
  - codecov
